### PR TITLE
api change

### PR DESCRIPTION
**Pull request by 21paradox**
api change

**What kind of change does this PR introduce?**

**Did you add tests for your changes?**

**Does this PR introduce a breaking change?**

**What needs to be documented once your changes are merged?**

---
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-scan/61)

### CODE REVIEW

**Review by Conflux-Dev — DISMISSED** [review]

**Review by AngeliaQ — DISMISSED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-scan/61)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by AngeliaQ — DISMISSED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-scan/61)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by AngeliaQ — DISMISSED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-scan/61)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by AngeliaQ — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-scan/61)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
